name: lint

on: [ pull_request ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 1024
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.8'
      - name: pre-commit
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha}}
          HEAD_SHA: ${{ github.event.pull_request.head.sha}}
        run: |
          python -m pip install pre-commit
          SETUPTOOLS_USE_DISTUTILS=stdlib pre-commit run --from-ref $BASE_SHA --to-ref $HEAD_SHA --all-files
