name: Run Unit Test

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install pip --upgrade
          pip install pytest
      - name: Test with pytest
        run: |
          PYTHONPATH=src pytest --log-level=debug --junitxml=junit_report.xml .
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@b9f6c61d965bcaa18acc02d6daf706373a448f02 # v1
        if: always()
        with:
          files: junit_report.xml
